<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CoreApiResponse" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="MongoRepo" Version="1.0.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
